version: "3.7"

services:
  prestashop:
    image: prestashop/prestashop:1.7
    restart: always
    ports:
      - "80:80"
    environment:
      - PS_DEV_MODE=${PS_DEV_MODE}
      - DB_SERVER=${DB_SERVER}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWD=${DB_PASSWD}
      - PS_INSTALL_AUTO=0
    volumes:
      - ./srv:/var/www/html
